CREATE TABLE IF NOT EXISTS airports (
  country_code TEXT PRIMARY KEY,
  iata TEXT NOT NULL,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lon DOUBLE PRECISION NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
