CREATE TABLE IF NOT EXISTS travel_attributes (
  codigo_pais TEXT PRIMARY KEY,
  playa INTEGER NOT NULL CHECK (playa BETWEEN 1 AND 10),
  cultural INTEGER NOT NULL CHECK (cultural BETWEEN 1 AND 10),
  naturaleza INTEGER NOT NULL CHECK (naturaleza BETWEEN 1 AND 10),
  familiar INTEGER NOT NULL CHECK (familiar BETWEEN 1 AND 10),
  mejor_epoca TEXT[] NOT NULL,
  duracion_optima INTEGER NOT NULL,
  actualizado_en TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO travel_attributes (codigo_pais, playa, cultural, naturaleza, familiar, mejor_epoca, duracion_optima)
SELECT code, playa, cultural, naturaleza, familiar, epoca, duracion
FROM (VALUES
  ('es', 9, 9, 8, 9, ARRAY['Mayo','Jun','Sep'], 7),
  ('fr', 6, 10, 7, 8, ARRAY['Jun','Jul','Sep'], 5),
  ('it', 8, 10, 7, 8, ARRAY['Mayo','Jun','Sep'], 7),
  ('pt', 9, 7, 7, 9, ARRAY['Mayo','Jun','Sep'], 7),
  ('gr', 9, 8, 6, 7, ARRAY['Mayo','Jun','Jul'], 7),
  ('tr', 9, 8, 6, 7, ARRAY['Mayo','Jun','Sep'], 10),
  ('us', 7, 8, 8, 8, ARRAY['Mayo','Jun','Sep'], 14),
  ('mx', 10, 9, 7, 9, ARRAY['Nov','Dic','Mar'], 10),
  ('br', 9, 6, 9, 7, ARRAY['Dic','Jan','Feb'], 10),
  ('ar', 5, 8, 6, 7, ARRAY['Mar','Apr','Oct'], 14),
  ('jp', 5, 10, 9, 7, ARRAY['Mar','Apr','Oct'], 10),
  ('th', 10, 7, 9, 6, ARRAY['Nov','Dic','Feb'], 14),
  ('vn', 7, 7, 9, 6, ARRAY['Nov','Dic','Feb'], 14),
  ('id', 10, 6, 9, 6, ARRAY['Mayo','Jun','Sep'], 14),
  ('au', 9, 6, 9, 8, ARRAY['Dic','Jan','Feb'], 14),
  ('nz', 7, 5, 10, 8, ARRAY['Dic','Jan','Feb'], 14),
  ('ma', 9, 7, 6, 8, ARRAY['Mar','Apr','Mayo'], 7),
  ('eg', 6, 10, 8, 6, ARRAY['Oct','Nov','Mar'], 7),
  ('za', 7, 6, 9, 7, ARRAY['Oct','Nov','Mar'], 10),
  ('gb', 4, 9, 6, 7, ARRAY['Mayo','Jun','Sep'], 5),
  ('de', 3, 8, 7, 8, ARRAY['Mayo','Jun','Sep'], 7),
  ('ca', 5, 6, 10, 9, ARRAY['Jun','Jul','Aug'], 14),
  ('cn', 5, 9, 7, 6, ARRAY['Apr','Mayo','Oct'], 10),
  ('in', 5, 10, 8, 5, ARRAY['Oct','Nov','Feb'], 14),
  ('hr', 8, 7, 7, 8, ARRAY['Mayo','Jun','Sep'], 7),
  ('cz', 2, 9, 6, 8, ARRAY['Mayo','Jun','Sep'], 5),
  ('pl', 2, 8, 7, 8, ARRAY['Mayo','Jun','Sep'], 7),
  ('nl', 5, 8, 6, 8, ARRAY['Mayo','Jun','Sep'], 5),
  ('ch', 3, 8, 10, 7, ARRAY['Dic','Jan','Feb'], 7),
  ('se', 3, 7, 8, 7, ARRAY['Jun','Jul','Aug'], 7),
  ('no', 2, 6, 9, 7, ARRAY['Jun','Jul','Aug'], 7),
  ('at', 2, 8, 8, 8, ARRAY['Mayo','Jun','Sep'], 7),
  ('ie', 4, 8, 8, 7, ARRAY['Mayo','Jun','Sep'], 5),
  ('dk', 4, 8, 7, 8, ARRAY['Jun','Jul','Aug'], 5),
  ('fi', 3, 7, 9, 7, ARRAY['Jun','Jul','Aug'], 7),
  ('is', 2, 6, 10, 6, ARRAY['Jun','Jul','Aug'], 7),
  ('hu', 3, 9, 6, 8, ARRAY['Mayo','Jun','Sep'], 4),
  ('bg', 7, 7, 6, 7, ARRAY['Jun','Jul','Aug'], 7),
  ('ee', 3, 8, 7, 7, ARRAY['Jun','Jul','Aug'], 4),
  ('lt', 4, 7, 7, 7, ARRAY['Jun','Jul','Aug'], 4),
  ('lv', 4, 7, 7, 7, ARRAY['Jun','Jul','Aug'], 4),
  ('si', 3, 7, 9, 8, ARRAY['Mayo','Jun','Sep'], 5),
  ('mt', 9, 8, 5, 8, ARRAY['Mayo','Jun','Oct'], 5),
  ('ae', 8, 7, 4, 7, ARRAY['Nov','Dic','Mar'], 5),
  ('sg', 6, 8, 6, 8, ARRAY['Feb','Mar','Apr'], 5),
  ('my', 8, 7, 8, 7, ARRAY['Mayo','Jun','Jul'], 10),
  ('ph', 10, 6, 8, 6, ARRAY['Nov','Dic','Mar'], 14),
  ('lk', 8, 8, 8, 6, ARRAY['Dic','Jan','Mar'], 10),
  ('cl', 6, 7, 9, 7, ARRAY['Nov','Dic','Mar'], 14),
  ('co', 7, 8, 9, 6, ARRAY['Dic','Jan','Jun'], 10),
  ('pe', 5, 10, 9, 6, ARRAY['Mayo','Jun','Sep'], 14),
  ('do', 10, 5, 6, 8, ARRAY['Nov','Dic','Apr'], 7),
  ('cu', 9, 8, 6, 6, ARRAY['Nov','Dic','Mar'], 10),
  ('pa', 7, 7, 8, 7, ARRAY['Dec','Jan','Mar'], 7),
  ('ec', 6, 7, 10, 6, ARRAY['Jun','Jul','Aug'], 10),
  ('ke', 6, 6, 10, 6, ARRAY['Jun','Jul','Sep'], 10),
  ('tz', 7, 5, 10, 6, ARRAY['Jun','Jul','Sep'], 10),
  ('gh', 6, 7, 7, 6, ARRAY['Nov','Dic','Jan'], 7),
  ('sa', 5, 8, 5, 5, ARRAY['Oct','Nov','Mar'], 7),
  ('jo', 4, 9, 7, 6, ARRAY['Mar','Apr','Oct'], 7),
  ('il', 6, 10, 6, 6, ARRAY['Mar','Apr','Oct'], 7),
  ('kr', 5, 9, 7, 7, ARRAY['Mar','Apr','Oct'], 7),
  ('be', 3, 9, 5, 8, ARRAY['Mayo','Jun','Sep'], 4)
) AS t(code, playa, cultural, naturaleza, familiar, epoca, duracion)
WHERE NOT EXISTS (SELECT 1 FROM travel_attributes);
