-- Actualizar places con country_code y risk_level por country_name
UPDATE places SET 
  country_code = CASE
    WHEN country_name IN ('España', 'Spain') THEN 'es'
    WHEN country_name IN ('Francia', 'France') THEN 'fr'
    WHEN country_name IN ('Alemania', 'Germany') THEN 'de'
    WHEN country_name IN ('Italia', 'Italy') THEN 'it'
    WHEN country_name IN ('Portugal', 'Portugal') THEN 'pt'
    WHEN country_name IN ('Reino Unido', 'United Kingdom') THEN 'gb'
    WHEN country_name IN ('Grecia', 'Greece') THEN 'gr'
    WHEN country_name IN ('Suiza', 'Switzerland') THEN 'ch'
    WHEN country_name IN ('Países Bajos', 'Netherlands') THEN 'nl'
    WHEN country_name IN ('Austria', 'Austria') THEN 'at'
    WHEN country_name IN ('Bélgica', 'Belgium') THEN 'be'
    WHEN country_name IN ('Irlanda', 'Ireland') THEN 'ie'
    WHEN country_name IN ('Noruega', 'Norway') THEN 'no'
    WHEN country_name IN ('Suecia', 'Sweden') THEN 'se'
    WHEN country_name IN ('Dinamarca', 'Denmark') THEN 'dk'
    WHEN country_name IN ('Finlandia', 'Finland') THEN 'fi'
    WHEN country_name IN ('Polonia', 'Poland') THEN 'pl'
    WHEN country_name IN ('República Checa', 'Czechia') THEN 'cz'
    WHEN country_name IN ('Hungría', 'Hungary') THEN 'hu'
    WHEN country_name IN ('Croacia', 'Croatia') THEN 'hr'
    WHEN country_name IN ('Eslovenia', 'Slovenia') THEN 'si'
    WHEN country_name IN ('Estonia', 'Estonia') THEN 'ee'
    WHEN country_name IN ('Letonia', 'Latvia') THEN 'lv'
    WHEN country_name IN ('Lituania', 'Lithuania') THEN 'lt'
    WHEN country_name IN ('Bulgaria', 'Bulgaria') THEN 'bg'
    WHEN country_name IN ('Malta', 'Malta') THEN 'mt'
    WHEN country_name IN ('Islandia', 'Iceland') THEN 'is'
    WHEN country_name IN ('Chile', 'Chile') THEN 'cl'
    WHEN country_name IN ('Japón', 'Japan') THEN 'jp'
    WHEN country_name IN ('Corea del Sur', 'South Korea') THEN 'kr'
    WHEN country_name IN ('Singapur', 'Singapore') THEN 'sg'
    WHEN country_name IN ('Australia', 'Australia') THEN 'au'
    WHEN country_name IN ('Nueva Zelanda', 'New Zealand') THEN 'nz'
    WHEN country_name IN ('Omán', 'Oman') THEN 'om'
    WHEN country_name IN ('Túnez', 'Tunisia') THEN 'tn'
    WHEN country_name IN ('Fiyi', 'Fiji') THEN 'fj'
    WHEN country_name IN ('Samoa', 'Samoa') THEN 'ws'
    WHEN country_name IN ('Trinidad y Tobago', 'Trinidad and Tobago') THEN 'tt'
    WHEN country_name IN ('Groenlandia', 'Greenland') THEN 'gl'
    WHEN country_name IN ('Uruguay', 'Uruguay') THEN 'uy'
    WHEN country_name IN ('Canadá', 'Canada') THEN 'ca'
    WHEN country_name IN ('Estados Unidos', 'United States') THEN 'us'
    WHEN country_name IN ('México', 'Mexico') THEN 'mx'
    WHEN country_name IN ('Colombia', 'Colombia') THEN 'co'
    WHEN country_name IN ('Perú', 'Peru') THEN 'pe'
    WHEN country_name IN ('Brasil', 'Brazil') THEN 'br'
    WHEN country_name IN ('Argentina', 'Argentina') THEN 'ar'
    WHEN country_name IN ('Tailandia', 'Thailand') THEN 'th'
    WHEN country_name IN ('Vietnam', 'Vietnam') THEN 'vn'
    WHEN country_name IN ('India', 'India') THEN 'in'
    WHEN country_name IN ('China', 'China') THEN 'cn'
    WHEN country_name IN ('Sudáfrica', 'South Africa') THEN 'za'
    WHEN country_name IN ('Egipto', 'Egypt') THEN 'eg'
    WHEN country_name IN ('Marruecos', 'Morocco') THEN 'ma'
    WHEN country_name IN ('Kenia', 'Kenya') THEN 'ke'
    WHEN country_name IN ('Turquía', 'Turkey') THEN 'tr'
    WHEN country_name IN ('Indonesia (Bali)', 'Indonesia') THEN 'id'
    WHEN country_name IN ('Laos', 'Laos') THEN 'la'
    WHEN country_name IN ('Malasia', 'Malaysia') THEN 'my'
    WHEN country_name IN ('Filipinas', 'Philippines') THEN 'ph'
    WHEN country_name IN ('Nepal', 'Nepal') THEN 'np'
    WHEN country_name IN ('Sri Lanka', 'Sri Lanka') THEN 'lk'
    WHEN country_name IN ('Catar', 'Qatar') THEN 'qa'
    WHEN country_name IN ('Jordania', 'Jordan') THEN 'jo'
    WHEN country_name IN ('Mozambique', 'Mozambique') THEN 'mz'
    WHEN country_name IN ('Argelia', 'Algeria') THEN 'dz'
    WHEN country_name IN ('Tanzania', 'Tanzania') THEN 'tz'
    WHEN country_name IN ('Ecuador', 'Ecuador') THEN 'ec'
    WHEN country_name IN ('Costa Rica', 'Costa Rica') THEN 'cr'
    WHEN country_name IN ('Panamá', 'Panama') THEN 'pa'
    WHEN country_name IN ('República Dominicana', 'Dominican Republic') THEN 'do'
    WHEN country_name IN ('Ghana', 'Ghana') THEN 'gh'
    WHEN country_name IN ('Etiopía', 'Ethiopia') THEN 'et'
    WHEN country_name IN ('Ruanda', 'Rwanda') THEN 'rw'
    WHEN country_name IN ('Senegal', 'Senegal') THEN 'sn'
    WHEN country_name IN ('Botsuana', 'Botswana') THEN 'bw'
    WHEN country_name IN ('Mauricio', 'Mauritius') THEN 'mu'
    WHEN country_name IN ('Bangladesh', 'Bangladesh') THEN 'bd'
    WHEN country_name IN ('Guatemala', 'Guatemala') THEN 'gt'
    WHEN country_name IN ('Jamaica', 'Jamaica') THEN 'jm'
    WHEN country_name IN ('Paraguay', 'Paraguay') THEN 'py'
    WHEN country_name IN ('Bolivia', 'Bolivia') THEN 'bo'
    WHEN country_name IN ('Albania', 'Albania') THEN 'al'
    WHEN country_name IN ('Georgia', 'Georgia') THEN 'ge'
    WHEN country_name IN ('Kazajistán', 'Kazakhstan') THEN 'kz'
    WHEN country_name IN ('Uzbekistán', 'Uzbekistan') THEN 'uz'
    WHEN country_name IN ('Kirguistán', 'Kyrgyzstan') THEN 'kg'
    WHEN country_name IN ('Tayikistán', 'Tajikistan') THEN 'tj'
    WHEN country_name IN ('Mongolia', 'Mongolia') THEN 'mn'
    WHEN country_name IN ('Armenia', 'Armenia') THEN 'am'
    WHEN country_name IN ('Azerbaiyán', 'Azerbaijan') THEN 'az'
    WHEN country_name IN ('Camboya', 'Cambodia') THEN 'kh'
    WHEN country_name IN ('Myanmar', 'Myanmar') THEN 'mm'
    WHEN country_name IN ('Arabia Saudita', 'Saudi Arabia') THEN 'sa'
    WHEN country_name IN ('Israel', 'Israel') THEN 'il'
    WHEN country_name IN ('Líbano', 'Lebanon') THEN 'lb'
    WHEN country_name IN ('Nigeria', 'Nigeria') THEN 'ng'
    WHEN country_name IN ('Pakistán', 'Pakistan') THEN 'pk'
    WHEN country_name IN ('Papúa Nueva Guinea', 'Papua New Guinea') THEN 'pg'
    WHEN country_name IN ('Venezuela', 'Venezuela') THEN 've'
    WHEN country_name IN ('Sudán', 'Sudan') THEN 'sd'
    WHEN country_name IN ('Afganistán', 'Afghanistan') THEN 'af'
    WHEN country_name IN ('Yemen', 'Yemen') THEN 'ye'
    WHEN country_name IN ('Siria', 'Syria') THEN 'sy'
    WHEN country_name IN ('Libia', 'Libya') THEN 'ly'
    WHEN country_name IN ('Haití', 'Haiti') THEN 'ht'
    ELSE country_code
  END,
  risk_level = CASE
    WHEN country_name IN ('España', 'Spain', 'Francia', 'France', 'Alemania', 'Germany', 'Italia', 'Italy', 'Portugal', 'Portugal', 'Reino Unido', 'United Kingdom', 'Grecia', 'Greece', 'Suiza', 'Switzerland', 'Países Bajos', 'Netherlands', 'Austria', 'Austria', 'Bélgica', 'Belgium', 'Irlanda', 'Ireland', 'Noruega', 'Norway', 'Suecia', 'Sweden', 'Dinamarca', 'Denmark', 'Finlandia', 'Finland', 'Polonia', 'Poland', 'República Checa', 'Czechia', 'Hungría', 'Hungary', 'Croacia', 'Croatia', 'Eslovenia', 'Slovenia', 'Estonia', 'Estonia', 'Letonia', 'Latvia', 'Lituania', 'Lithuania', 'Bulgaria', 'Bulgaria', 'Malta', 'Malta', 'Islandia', 'Iceland', 'Chile', 'Chile', 'Japón', 'Japan', 'Corea del Sur', 'South Korea', 'Singapur', 'Singapore', 'Australia', 'Australia', 'Nueva Zelanda', 'New Zealand', 'Omán', 'Oman', 'Túnez', 'Tunisia', 'Fiyi', 'Fiji', 'Samoa', 'Samoa', 'Trinidad y Tobago', 'Trinidad and Tobago', 'Groenlandia', 'Greenland', 'Uruguay', 'Uruguay', 'Canadá', 'Canada', 'Estados Unidos', 'United States') THEN 'sin-riesgo'
    WHEN country_name IN ('México', 'Mexico', 'Colombia', 'Colombia', 'Perú', 'Peru', 'Brasil', 'Brazil', 'Argentina', 'Argentina', 'Tailandia', 'Thailand', 'Vietnam', 'Vietnam', 'India', 'India', 'China', 'China', 'Sudáfrica', 'South Africa', 'Egipto', 'Egypt', 'Marruecos', 'Morocco', 'Kenia', 'Kenya', 'Turquía', 'Turkey', 'Indonesia (Bali)', 'Indonesia', 'Laos', 'Laos', 'Malasia', 'Malaysia', 'Filipinas', 'Philippines', 'Nepal', 'Nepal', 'Sri Lanka', 'Sri Lanka', 'Catar', 'Qatar', 'Jordania', 'Jordan', 'Mozambique', 'Mozambique', 'Argelia', 'Algeria', 'Tanzania', 'Tanzania', 'Ecuador', 'Ecuador', 'Costa Rica', 'Costa Rica', 'Panamá', 'Panama', 'República Dominicana', 'Dominican Republic', 'Ghana', 'Ghana', 'Etiopía', 'Ethiopia', 'Ruanda', 'Rwanda', 'Senegal', 'Senegal', 'Botsuana', 'Botswana', 'Mauricio', 'Mauritius', 'Bangladesh', 'Bangladesh', 'Guatemala', 'Guatemala', 'Jamaica', 'Jamaica', 'Paraguay', 'Paraguay', 'Bolivia', 'Bolivia', 'Albania', 'Albania', 'Georgia', 'Georgia', 'Kazajistán', 'Kazakhstan', 'Uzbekistán', 'Uzbekistan', 'Kirguistán', 'Kyrgyzstan', 'Tayikistán', 'Tajikistan', 'Mongolia', 'Mongolia', 'Armenia', 'Armenia', 'Azerbaiyán', 'Azerbaijan') THEN 'bajo'
    WHEN country_name IN ('Camboya', 'Cambodia', 'Myanmar', 'Myanmar', 'Arabia Saudita', 'Saudi Arabia', 'Israel', 'Israel', 'Líbano', 'Lebanon', 'Nigeria', 'Nigeria', 'Pakistán', 'Pakistan', 'Papúa Nueva Guinea', 'Papua New Guinea') THEN 'medio'
    WHEN country_name IN ('Venezuela', 'Venezuela') THEN 'alto'
    WHEN country_name IN ('Sudán', 'Sudan', 'Afganistán', 'Afghanistan', 'Yemen', 'Yemen', 'Siria', 'Syria', 'Libia', 'Libya', 'Haití', 'Haiti') THEN 'muy-alto'
    ELSE risk_level
  END
WHERE country_name IS NOT NULL;
